---
title: "Fabricante"
params:
  fabricante: audi
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
# https://rmarkdown.rstudio.com/developer_parameterized_reports

knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
load("datos/millas.rda")
load("modelo.rds")

```

```{r}
fab <- millas %>%
  filter(fabricante == params$fabricante) %>%
  select(modelo, anio, clase, cilindros, autopista)

pred <- predict(modelo, fab)

fab <- fab %>%
  mutate(pred = round(pred)) 

datatable(fab)
```

```{r, fig.width = 9}

fab %>%
  mutate(
    id = row_number(),
    anio = as.character(anio)
    ) %>%
  ggplot() +
  geom_col(aes(id, autopista, fill = anio), alpha = 0.5) +
  geom_col(aes(id, pred, fill = anio), color = "darkgray", alpha = 0) +
  geom_text(aes(id, 0.1, label = modelo), size = 2.5, hjust = 0) +
  geom_text(aes(id, autopista, label = autopista), size = 2, hjust = 1) +
  geom_text(aes(id, pred, label = pred), size = 2.5, hjust = 0) +
  coord_flip() +
  theme_void() +
  labs(title = str_to_title(params$fabricante), fill = "Autopista")
```



