// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parallelInnerProduct
double parallelInnerProduct(NumericVector lhs, NumericVector rhs);
RcppExport SEXP RcppParallelExample_parallelInnerProduct(SEXP lhsSEXP, SEXP rhsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type lhs(lhsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rhs(rhsSEXP);
    __result = Rcpp::wrap(parallelInnerProduct(lhs, rhs));
    return __result;
END_RCPP
}
// parallelLog
NumericVector parallelLog(NumericVector input);
RcppExport SEXP RcppParallelExample_parallelLog(SEXP inputSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type input(inputSEXP);
    __result = Rcpp::wrap(parallelLog(input));
    return __result;
END_RCPP
}
